### ISSUE TITLE
convert

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#12]
da stringa di cifre a intero a double a stringa

**Comment by ClaudioTazza** [comment]
Risulta la mancanza della funzione?

**Comment by FabioZTessitore** [comment]
Mi devo ancora ritirare. Vedremo

Il venerdì 27 gennaio 2017, lucifero55 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
c'è

**Comment by ClaudioTazza** [comment]
Non lo trovo.. Se lo faccio io va bene lo stesso? haha

**Comment by FabioZTessitore** [comment]
Vediamo

Il 27 gen 2017 11:40 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
halp

**Comment by ClaudioTazza** [comment]
non funge bene

**Comment by FabioZTessitore** [comment]
riga 15, cosa volevi fare?

**Comment by ClaudioTazza** [comment]
Mettere il numero **num** nella stringa **v**

**Comment by FabioZTessitore** [comment]
Num di che tipo è?

Il 30 gen 2017 4:02 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
in teoria double, ma quando vado a stamparlo poco prima esce 0.
Direi di risolvere prima la riga 12

**Comment by FabioZTessitore** [comment]
ho visto che hai corretto (parzialmente) la riga 15.
Possiamo parlare della 12. Cosa volevi fare?

**Comment by ClaudioTazza** [comment]
volevo convertire num da intero a double

**Comment by FabioZTessitore** [comment]
volevi ...
analizza cosa fa quella riga

**Comment by ClaudioTazza** [comment]
mettere nella variabile num il valore di num versione double?

**Comment by FabioZTessitore** [comment]
vediamo se ho capito bene.
hai num che è intera, la converti in double ... e magicamente vuoi memorizzare il risultato in num (che è sempre una variabile intera)

**Comment by ClaudioTazza** [comment]
Dovrei crearne un'altra?

**Comment by FabioZTessitore** [comment]
dovresti

**Comment by ClaudioTazza** [comment]
ora perche' da errori

**Comment by FabioZTessitore** [comment]
perché la correzione alla riga 15 (ora diventata 16) era parziale

**Comment by ClaudioTazza** [comment]
Non arrivo al problema

**Comment by ClaudioTazza** [comment]
devo cambiare funzione?

**Comment by FabioZTessitore** [comment]
La funzione è giusta. Ti rendi conto che non ci va in v?

Il 30 gen 2017 6:39 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
e come dovrei fare?

**Comment by ClaudioTazza** [comment]
ingrandire v o diminuire num?

**Comment by FabioZTessitore** [comment]
Il problema di num non è la dimensione numerica (lo devi convertire in
stringa)
V è troppo piccola

Il 30 gen 2017 6:56 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Va bene cosi'?

**Comment by FabioZTessitore** [comment]
Hai il coraggio di chiedere?

**Comment by ClaudioTazza** [comment]
beh funziona

**Comment by FabioZTessitore** [comment]
è solo un caso. stai scrivendo a caso nella memoria
