### ISSUE TITLE
sizeof

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#2]
dimmi se chiaro

**Comment by ClaudioTazza** [comment]
Con "su questa macchina" intende che ogni computer da un diverso numero di byte?

**Comment by FabioZTessitore** [comment]
macchina = hardware + sistema operativo + compilatore

**Comment by ClaudioTazza** [comment]
Non ha risposto alla mia domanda

**Comment by FabioZTessitore** [comment]
ho risposto
