### ISSUE TITLE
funzioni per lavorare con i caratteri

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#3]
Nel file `ctype.h` sono presenti i prototipi
di molte funzioni utili per lavorare con i caratteri.

![ctype](https://cloud.githubusercontent.com/assets/3002194/22019220/deae0da2-dcb2-11e6-8454-78367d97c8ed.png)

**Comment by ClaudioTazza** [comment]
Non c'è nessun file ctype.h

**Comment by FabioZTessitore** [comment]
dove lo stai cercando?

**Comment by ClaudioTazza** [comment]
non mi trovo

**Comment by ClaudioTazza** [comment]
Cosa si intende per valore vero?

**Comment by FabioZTessitore** [comment]
Di che parli?

Il giovedì 19 gennaio 2017, lucifero55 <notifications@github.com> ha
scritto:

**Comment by ClaudioTazza** [comment]
Se guarda nella cartella sizeof ho scritto un programma che stampa il valore che restituisce la funzione.
Per quello che sta scritto sopra dovrebbe restituire un valore vero, nel mio caso torna 8.

**Comment by FabioZTessitore** [comment]
Ah. Vero nel senso di True. In C è vero se non zero

Il giovedì 19 gennaio 2017, lucifero55 <notifications@github.com> ha
scritto:

**Comment by ClaudioTazza** [comment]
ok chiaro
