### ISSUE TITLE
i/o

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#5]
![i-o](https://cloud.githubusercontent.com/assets/3002194/22149726/b40d2690-df15-11e6-8d46-a8357eb4adb9.png)

**Comment by ClaudioTazza** [comment]
piu' o meno chiari, forse se domani mi fa vedere un po' di esempi e' meglio

**Comment by ClaudioTazza** [comment]
non ha dei file già pronti per farmi capire?

**Comment by FabioZTessitore** [comment]
sono quasi tutte funzioni che conosci già

**Comment by ClaudioTazza** [comment]
chiaro
