### ISSUE TITLE
confronto

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#7]
![confronto](https://cloud.githubusercontent.com/assets/3002194/22157940/15bcdeac-df3a-11e6-8e71-e125c0fd0a00.png)

**Comment by ClaudioTazza** [comment]
Come si fa a stabilire se una stringa sia maggiore o minore di un'altra?

**Comment by FabioZTessitore** [comment]
Mai sentito parlare di ordine alfabetico

Il 21 gen 2017 9:44 AM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Ok chiaro
