### ISSUE TITLE
Ricerca nelle stringhe

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Stringhe#8]
![ricerca1](https://cloud.githubusercontent.com/assets/3002194/22175290/5bd4b938-dff2-11e6-9e43-0fd63fc242cc.png)
![ricerca2](https://cloud.githubusercontent.com/assets/3002194/22175295/64ae58ac-dff2-11e6-865e-a200ee52a8fb.png)

**Comment by ClaudioTazza** [comment]
ok
